# Generated by Django 6.0.4 on 2026-04-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Benchmark', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('results_json', models.TextField()),
                ('dashboard_image', models.ImageField(blank=True, upload_to='dashboards/')),
                ('gantt_image', models.ImageField(blank=True, upload_to='gantts/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
